defaultNamespace: monitoring
helm:
  releaseName: kube-prometheus-stack
  chart: ${OCI_HELM_PREFIX}/kube-prometheus-stack
  version: "${CHART_VER_PROMETHEUS_STACK}"
  valuesFiles:
    - values.yaml
targets:
  - clusterName: ${FLEET_TARGET_CLUSTER}
