apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-redis
  namespace: gitlab
spec:
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: gitlab-redis
  endpoints:
    - port: redis-exporter
      targetPort: 9121
      interval: 30s
