apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-valkey-credentials
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: harbor-valkey-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: services/harbor/valkey
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: services/harbor/valkey
        property: password
