apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storage-autoscaler-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - storage-autoscaler
  selector:
    matchLabels:
      app.kubernetes.io/name: storage-autoscaler
  endpoints:
    - port: metrics
