apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-prometheus
  namespace: monitoring
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: oauth2-proxy-prometheus
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: oidc/prometheus-oidc
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: oidc/prometheus-oidc
        property: cookie-secret
