apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: identity-portal
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["identity-portal"]
  selector:
    matchLabels:
      app: identity-portal
      component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
