//go:build !ignore_autogenerated

/*
Copyright 2026 Volume Autoscaler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerReference) DeepCopyInto(out *ControllerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerReference.
func (in *ControllerReference) DeepCopy() *ControllerReference {
	if in == nil {
		return nil
	}
	out := new(ControllerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCStatus) DeepCopyInto(out *PVCStatus) {
	*out = *in
	out.CurrentSize = in.CurrentSize.DeepCopy()
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleSize != nil {
		in, out := &in.LastScaleSize, &out.LastScaleSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCStatus.
func (in *PVCStatus) DeepCopy() *PVCStatus {
	if in == nil {
		return nil
	}
	out := new(PVCStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAutoscaler) DeepCopyInto(out *VolumeAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAutoscaler.
func (in *VolumeAutoscaler) DeepCopy() *VolumeAutoscaler {
	if in == nil {
		return nil
	}
	out := new(VolumeAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAutoscalerList) DeepCopyInto(out *VolumeAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAutoscalerList.
func (in *VolumeAutoscalerList) DeepCopy() *VolumeAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(VolumeAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAutoscalerSpec) DeepCopyInto(out *VolumeAutoscalerSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	out.MaxSize = in.MaxSize.DeepCopy()
	if in.IncreaseMinimum != nil {
		in, out := &in.IncreaseMinimum, &out.IncreaseMinimum
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CooldownPeriod != nil {
		in, out := &in.CooldownPeriod, &out.CooldownPeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAutoscalerSpec.
func (in *VolumeAutoscalerSpec) DeepCopy() *VolumeAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAutoscalerStatus) DeepCopyInto(out *VolumeAutoscalerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.PVCs != nil {
		in, out := &in.PVCs, &out.PVCs
		*out = make([]PVCStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAutoscalerStatus.
func (in *VolumeAutoscalerStatus) DeepCopy() *VolumeAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAutoscalerTarget) DeepCopyInto(out *VolumeAutoscalerTarget) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerRef != nil {
		in, out := &in.ControllerRef, &out.ControllerRef
		*out = new(ControllerReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAutoscalerTarget.
func (in *VolumeAutoscalerTarget) DeepCopy() *VolumeAutoscalerTarget {
	if in == nil {
		return nil
	}
	out := new(VolumeAutoscalerTarget)
	in.DeepCopyInto(out)
	return out
}
