apiVersion: v1
kind: Service
metadata:
  name: backup-minio
  namespace: backup
  labels:
    app: backup-minio
spec:
  type: ClusterIP
  selector:
    app: backup-minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
