apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-init
  namespace: backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-secrets
  namespace: backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: backup
