apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # GitLab monitoring
  - configmap-dashboard-gitlab.yaml
  - service-monitor.yaml
  - service-monitor-redis.yaml
  - gitlab-alerts.yaml
  # Runner monitoring
  - configmap-dashboard-gitlab-runners.yaml
  - runners-service-monitor.yaml
  - gitlab-runner-alerts.yaml
