---
apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: prometheus
  namespace: monitoring
spec:
  target:
    pvcName: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  prometheusURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  thresholdPercent: 80
  maxSize: 200Gi
  increasePercent: 25
  increaseMinimum: 5Gi
  pollInterval: 60s
  cooldownPeriod: 5m
---
apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: loki
  namespace: monitoring
spec:
  target:
    selector:
      matchLabels:
        app: loki
  prometheusURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  thresholdPercent: 80
  maxSize: 200Gi
  increasePercent: 25
  increaseMinimum: 5Gi
  pollInterval: 120s
  cooldownPeriod: 5m
---
apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: grafana-pg
  namespace: database
spec:
  target:
    selector:
      matchLabels:
        cnpg.io/cluster: grafana-pg
    controllerRef:
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: grafana-pg
  prometheusURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  thresholdPercent: 80
  maxSize: 50Gi
  increasePercent: 25
  increaseMinimum: 5Gi
  pollInterval: 120s
  cooldownPeriod: 10m
