defaultNamespace: argocd
helm:
  releaseName: argocd
  chart: ${OCI_HELM_PREFIX}/argo-cd
  version: "${CHART_VER_ARGOCD}"
  valuesFiles:
    - values.yaml
targets:
  - clusterName: ${FLEET_TARGET_CLUSTER}
