defaultNamespace: argocd
helm:
  releaseName: argocd
  chart: ${OCI_HELM_PREFIX}/argo-cd
  version: "${CHART_VER_ARGOCD}"
  valuesFiles:
    - values.yaml
dependsOn:
  - name: gitops-argocd-init
  - name: argocd-credentials
targets:
  - clusterName: ${FLEET_TARGET_CLUSTER}
