apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-rollouts
  namespace: argo-rollouts
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: oauth2-proxy-rollouts
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: oidc/rollouts-oidc
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: oidc/rollouts-oidc
        property: cookie-secret
