apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: minio
spec:
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      app: minio
  endpoints:
    - port: s3
      path: /minio/v2/metrics/cluster
      interval: 30s
    - port: s3
      path: /minio/v2/metrics/bucket
      interval: 30s
    - port: s3
      path: /minio/v2/metrics/node
      interval: 30s
