# CNPG Operator Helm values
crds:
  create: true

# HA: 2 replicas with leader election (built-in)
replicaCount: 2
nodeSelector:
  workload-type: general
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: cloudnative-pg

monitoring:
  podMonitorEnabled: true
  podMonitorAdditionalLabels:
    release: kube-prometheus-stack

config:
  data:
    INHERITED_ANNOTATIONS: "kustomize.toolkit.fluxcd.io/*"
    INHERITED_LABELS: "app.kubernetes.io/*"
