apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: database
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: database
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-database"
          serviceAccountRef:
            name: "external-secrets"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-writer
  namespace: database
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-writer-database"
          serviceAccountRef:
            name: "external-secrets"
