apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-golden-images-token
  namespace: argo-workflows
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-golden-images-token
    creationPolicy: Owner
  data:
    - secretKey: GITLAB_USER
      remoteRef:
        key: services/ci/golden-image-watcher
        property: username
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: services/ci/golden-image-watcher
        property: token
    - secretKey: GITLAB_REPO_URL
      remoteRef:
        key: services/ci/golden-image-watcher
        property: repo-url
