apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argo-workflows
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: argo-workflows
spec:
  provider:
    vault:
      server: "${VAULT_INTERNAL_URL}"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-argo-workflows"
          serviceAccountRef:
            name: "external-secrets"
