apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  namespaceSelector:
    matchNames:
      - argo-workflows
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-workflow-controller
  endpoints:
    - port: metrics
