apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: services/database/grafana-pg
        property: username
    - secretKey: password
      remoteRef:
        key: services/database/grafana-pg
        property: password
