apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-secrets
  namespace: monitoring
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: monitoring
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-monitoring"
          serviceAccountRef:
            name: "eso-secrets"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-writer
  namespace: monitoring
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-writer-monitoring"
          serviceAccountRef:
            name: "eso-secrets"
