apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-secrets
  namespace: kube-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: kube-system
spec:
  provider:
    vault:
      server: "${VAULT_INTERNAL_URL}"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-kube-system"
          serviceAccountRef:
            name: "eso-secrets"
