apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
  labels:
    app.kubernetes.io/name: cluster-autoscaler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-autoscaler
