apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  namespaceSelector:
    matchNames:
      - cluster-autoscaler
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-autoscaler
  endpoints:
    - port: http
