apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-license
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-license
    creationPolicy: Owner
  data:
    - secretKey: activation-code
      remoteRef:
        key: services/gitlab
        property: activation-code
    - secretKey: license-file
      remoteRef:
        key: services/gitlab
        property: license-file
