apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: identity-portal-success-rate
  namespace: identity-portal
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(identity_portal_http_requests_total{status!~"5.."}[2m]))
            / sum(rate(identity_portal_http_requests_total[2m]))
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: identity-portal-error-rate
  namespace: identity-portal
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 5
      successCondition: result[0] <= 0.05
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(identity_portal_http_requests_total{status=~"5.."}[2m]))
            / sum(rate(identity_portal_http_requests_total[2m]))
