apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # Keycloak core
  - keycloak/rbac.yaml
  - keycloak/external-secret.yaml
  - keycloak/service.yaml
  - keycloak/service-headless.yaml
  - keycloak/deployment.yaml
  - keycloak/hpa.yaml
  # PostgreSQL CNPG
  - postgres/external-secret.yaml
  - postgres/keycloak-pg-cluster.yaml
  - postgres/keycloak-pg-scheduled-backup.yaml
  # Ingress
  - gateway.yaml
  - httproute.yaml
  # Volume autoscalers (PVC expansion)
  - volume-autoscalers.yaml
  # Monitoring
  - monitoring/
