apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-dashboard-harbor.yaml
  - service-monitor.yaml
  - service-monitor-valkey.yaml
  - service-monitor-minio.yaml
  - configmap-dashboard-minio.yaml
  - harbor-alerts.yaml
  - minio-alerts.yaml
