apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
      remoteRef:
        key: services/keycloak/admin-secret
        property: KC_BOOTSTRAP_ADMIN_USERNAME
    - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: services/keycloak/admin-secret
        property: KC_BOOTSTRAP_ADMIN_PASSWORD
    - secretKey: KC_BOOTSTRAP_ADMIN_CLIENT_ID
      remoteRef:
        key: services/keycloak/admin-secret
        property: KC_BOOTSTRAP_ADMIN_CLIENT_ID
    - secretKey: KC_BOOTSTRAP_ADMIN_CLIENT_SECRET
      remoteRef:
        key: services/keycloak/admin-secret
        property: KC_BOOTSTRAP_ADMIN_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: services/keycloak/postgres-secret
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: services/keycloak/postgres-secret
        property: POSTGRES_PASSWORD
