---
apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: vault-data-0
  namespace: vault
spec:
  target:
    pvcName: data-vault-0
  prometheusURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  thresholdPercent: 80
  maxSize: 50Gi
  increasePercent: 25
  increaseMinimum: 5Gi
  pollInterval: 120s
  cooldownPeriod: 10m
---
apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: vault-data-1
  namespace: vault
spec:
  target:
    pvcName: data-vault-1
  prometheusURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  thresholdPercent: 80
  maxSize: 50Gi
  increasePercent: 25
  increaseMinimum: 5Gi
  pollInterval: 120s
  cooldownPeriod: 10m
---
apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: vault-data-2
  namespace: vault
spec:
  target:
    pvcName: data-vault-2
  prometheusURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  thresholdPercent: 80
  maxSize: 50Gi
  increasePercent: 25
  increaseMinimum: 5Gi
  pollInterval: 120s
  cooldownPeriod: 10m
